package com.example.propertystore.constants;

public enum PropertyStoreApiName {
	PROPERTY_STORE_GET_PROPERTY, PROPERTY_STORE_GET_PROPERTIES, PROPERTY_STORE_DELETE_PROPERTY,
	PROPERTY_STORE_ADD_PROPERTY, PROPERTY_STORE_EDIT_PROPERTY;
}
